version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - ./gradlew build

branches:
  only:
    - 1.12.2

cache:
  - C:\Users\appveyor\.gradle


artifacts:
  - path: build/libs/*.jar
