version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - ./gradlew build

branches:
  only:
    - master
    - development

cache:
  - C:\Users\appveyor\.gradle


artifacts:
  - path: build\libs
    name: peters-exclusives*
